### PR TITLE
Add missing word and clarify sentence

### PR DESCRIPTION
**Pull request by alainkaegi**
It seems like a noun is missing after "multiple".  Then I feel like it might be worth emphasizing that we are talking about the same client/server pair, but I don't feel as strongly about this latter part.

The title could be changed to "Add missing noun and clarify sentence" although feel free to modify as necessary.

### CODE REVIEW

**Comment by Ivan-Velickovic** [comment]
"when there are multiple services from the same client to the same server" is better but doesn't sound 100% right because "services" don't make sense in the context of a client. I think it would be better to have something like "when a server has multiple services for a client to invoke."

**Comment by alainkaegi** [comment]
That sounds great.

**Comment by Ivan-Velickovic** [comment]
Cool, would you mind updating the PR to that?

**Comment by alainkaegi** [comment]
I added a commit to patch-1 to fix the text as you suggested.  I've done this through the website interface.  I'm not sure if there is an easy way to merge the two commits into a single one.  But I think you should be able to do so when you dispose of the pull request.  If it's not convenient for you, I can see if I can do so from my end.  I may end up creating a new pull request instead.

**Comment by Ivan-Velickovic** [comment]
The GitHub UI lets me squash the commit, so I've done that now. Thanks again for the PR.

**Pull request merged**
